# Generated by Django 5.2.6 on 2026-06-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
