# Generated by Django 5.2.6 on 2026-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day_type',
            field=models.CharField(blank=True, choices=[('Full_Day', 'Full Day'), ('Three_Quarter_Day', 'Three Quarter Day'), ('Half_Day', 'Half Day'), ('Short_Day', 'Short Day')], max_length=20, null=True),
        ),
    ]
